#项目名称
spring:
  application:
    name: product

  #配置数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
  jpa: 
    show-sql: true
      
eureka:
  client:
    service-url:
      #将该服务注册到：http://localhost:8761/eureka/ 这个服务中心
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8762
      
      


      
